# Generated by Django 5.1.6 on 2025-03-04 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThriftStores',
            fields=[
                ('shopid', models.BigAutoField(db_column='ShopID', primary_key=True, serialize=False)),
                ('shopname', models.CharField(db_column='ShopName')),
                ('formattedaddress', models.TextField(blank=True, db_column='FormattedAddress', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('shortdescription', models.TextField(blank=True, db_column='ShortDescription', null=True)),
                ('pricerange', models.TextField(blank=True, db_column='PriceRange', null=True)),
                ('specialty', models.TextField(blank=True, db_column='Specialty', null=True)),
                ('popupstarttime', models.TimeField(blank=True, db_column='PopUpStartTime', null=True)),
                ('hasfittingrooms', models.BooleanField(blank=True, db_column='HasFittingRooms', null=True)),
                ('parkingavailability', models.TextField(blank=True, db_column='ParkingAvailability', null=True)),
                ('review', models.TextField(blank=True, db_column='Review', null=True)),
            ],
            options={
                'db_table': 'thrift_stores',
                'db_table_comment': 'A Relation Containing Information Of Each Thrift Shop',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.BigAutoField(db_column='userid', primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, db_column='username', null=True)),
                ('clothing', models.TextField(blank=True, db_column='clothing', null=True)),
                ('budget', models.TextField(blank=True, db_column='budget', null=True)),
                ('shoppingenvironment', models.TextField(blank=True, db_column='shoppingenvironment', null=True)),
                ('organization', models.TextField(blank=True, db_column='organization', null=True)),
                ('interest', models.TextField(blank=True, db_column='interest', null=True)),
            ],
            options={
                'db_table': 'users_pref',
                'db_table_comment': 'A Relation Containing Information Of Users Preferences',
            },
        ),
        migrations.CreateModel(
            name='FavoriteShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.ForeignKey(db_column='shopid', on_delete=django.db.models.deletion.CASCADE, to='ThriftNotice.thriftstores')),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to='ThriftNotice.users')),
            ],
            options={
                'db_table': 'favorite_shops',
                'db_table_comment': 'A table storing favorite shops for each user.',
                'unique_together': {('userid', 'shopid')},
            },
        ),
    ]
