# Generated by Django 5.1.6 on 2025-03-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0002_alter_favoriteshop_shopid_alter_favoriteshop_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopid', models.ForeignKey(db_column='shopid', on_delete=django.db.models.deletion.CASCADE, to='ThriftNotice.thriftstores')),
            ],
            options={
                'db_table': 'users_review',
                'db_table_comment': 'A table storing users reviews',
            },
        ),
    ]
