# Generated by Django 5.1.6 on 2025-02-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thriftstores',
            options={},
        ),
    ]
