# Generated by Django 5.1.6 on 2025-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0003_usersreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersreview',
            name='review',
            field=models.TextField(db_column='reviews', default='no review'),
            preserve_default=False,
        ),
    ]
