# Generated by Django 5.1.6 on 2025-02-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0004_users_alter_thriftstores_popupstarttime'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='users',
            table_comment='A Relation Containing Information Of Users Preferences',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users_pref',
        ),
    ]
