# Generated by Django 5.1.6 on 2025-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0005_alter_users_table_comment_alter_users_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='budget',
            field=models.TextField(db_column='budget'),
        ),
    ]
