# Generated by Django 5.1.6 on 2025-02-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0005_thriftstores_review'),
        ('ThriftNotice', '0006_alter_users_budget'),
    ]

    operations = [
    ]
