# Generated by Django 5.1.6 on 2025-02-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0008_users_usernmae_alter_users_budget_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='usernmae',
            new_name='username',
        ),
    ]
