# Generated by Django 5.1.6 on 2025-02-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0009_rename_usernmae_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteshop',
            name='id',
        ),
        migrations.AlterField(
            model_name='favoriteshop',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ThriftNotice.users'),
        ),
    ]
