# Generated by Django 5.1.6 on 2025-03-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0010_remove_favoriteshop_id_alter_favoriteshop_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteshop',
            options={'managed': False},
        ),
    ]
