# Generated by Django 5.1.6 on 2025-03-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftNotice', '0011_alter_favoriteshop_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteshop',
            options={},
        ),
    ]
